### ISSUE TITLE
Pixel Art Cat

### ISSUE THREAD

**Issue by Blumenkol** [infomediadesign/Paws_of_Memories#1]
Definition of Done: Finished Pixel Art wherefrom Animation can be started. Animation will be done in next issue.

**Comment by Tamina345** [comment]
Charakter is one title big (as big as boulders and walls).
Tile Dimentions (Level of detail): **24x24 p**

**Comment by LF-Cheeseburger** [comment]
![Paws_Of_Memories_Vorlage_Katze](https://user-images.githubusercontent.com/126563793/233488645-b6e2cc20-a8b5-4b3a-af7d-e514c40c93dc.png)
![Farbkodierung](https://user-images.githubusercontent.com/126563793/233489053-55fa5ce7-f4e1-48c8-832e-cb958b6f71f7.png)


Template done! The uploaded document is only a PNG of the template because github doesn't support the aseprite-file. The real template is send via mail. Also, color coding was added for better transparency.
